# Generated by Django 3.2.4 on 2021-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.TextField(max_length=200)),
                ('todo_description', models.TextField(max_length=250)),
                ('todo_status', models.TextField(choices=[('ongoing', 'ongoing'), ('done', 'done')])),
                ('todo_mode', models.TextField(choices=[('issues', 'issues'), ('goal', 'goal')])),
                ('todo_created', models.DateTimeField(auto_now_add=True)),
                ('todo_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
