# Generated by Django 3.2.4 on 2021-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_mode',
            field=models.TextField(choices=[('issues', 'issues'), ('Goal', 'Goal')]),
        ),
    ]
